"""Shield commands - e2e 测试编写 (B 级).

Shield 职责: 按 test-plan §6 写 e2e 测试 (Playwright/testclient/DB 直查)。
B 级 agent - 方法固定, 省成本。
lk 提供: 运行 e2e + 按规范 commit。
"""
import argparse
import subprocess
import sys
from pathlib import Path

from ._common import git


def register(subparsers):
    parser = subparsers.add_parser('shield', help='e2e 测试编写 (Shield, B 级)')
    sub = parser.add_subparsers(dest='command', required=True, metavar='<command>')

    p = sub.add_parser('run-e2e', help='运行 e2e 测试')
    p.add_argument('--spec', default='', help='spec-id (可选, 过滤)')
    p.add_argument('--browser', default='chromium', choices=['chromium', 'firefox', 'webkit'])

    p = sub.add_parser('commit-e2e', help='提交 e2e 测试 (按规范)')
    p.add_argument('--spec', required=True)
    p.add_argument('--message', required=True)

    p = sub.add_parser('scaffold', help='生成 e2e 测试骨架 (Playwright/testclient/DB 三种模板)')
    p.add_argument('--type', required=True, choices=['playwright', 'testclient', 'db'])
    p.add_argument('--scenario', required=True, help='场景名, 例 user_login_flow')
    p.add_argument('--ac-id', required=True, help='AC-FRXXXX-YY 引用')


def run(args):
    handlers = {
        'run-e2e': cmd_run_e2e,
        'commit-e2e': cmd_commit_e2e,
        'scaffold': cmd_scaffold,
    }
    return handlers.get(args.command, lambda _: 1)(args) or 0


def cmd_run_e2e(args):
    """Run e2e tests."""
    cwd = Path.cwd()
    e2e_path = '.louke/project/specs/{}/tests/e2e/'.format(args.spec) if args.spec else '.louke/project/specs/*/tests/e2e/'

    print(f"=== Run E2E ===")
    print(f"Path: {e2e_path}")
    print(f"Browser: {args.browser}")

    # Playwright 默认调用
    result = subprocess.run(
        ['python3', '-m', 'pytest', e2e_path, '-q', '--tb=short',
         '--browser', args.browser],
        cwd=cwd,
    )
    return result.returncode


def cmd_commit_e2e(args):
    """Commit e2e tests with proper format."""
    cwd = Path.cwd()
    spec_path = f".louke/project/specs/{args.spec}/tests/e2e/"

    print(f"=== Commit E2E ===")
    print(f"Spec path: {spec_path}")
    print(f"Message: {args.message}")

    cmds = [
        ['git', 'add', spec_path],
        ['git', 'commit', '-m', f'e2e: {args.message}'],
        ['git', 'push'],
    ]
    for cmd in cmds:
        rc, out, err = git(*cmd[1:], cwd=cwd)
        if rc != 0:
            print(f"failed: {' '.join(cmd)}\n{err}", file=sys.stderr)
            return rc
    print("✓ E2E committed and pushed")
    return 0


def cmd_scaffold(args):
    """生成 e2e 测试骨架模板.

    路径与 cmd_commit_e2e 对齐: .louke/project/specs/{spec}/tests/e2e/
    (e2e 测试属于 spec 范围, 不放顶层 tests/, 避免跨 spec 互相干扰)
    """
    cwd = Path.cwd()
    spec_path = f".louke/project/specs/{args.spec}/tests/e2e"
    target_dir = cwd / spec_path
    target_dir.mkdir(parents=True, exist_ok=True)
    target_file = target_dir / f'test_{args.scenario}.py'

    templates = {
        'playwright': f'''"""E2E test: {args.scenario} (AC: {args.ac_id}).

Generated by lk shield scaffold. Test framework: Playwright.
"""
import pytest
from playwright.sync_api import Page


@pytest.mark.e2e
def test_{args.scenario}(page: Page):
    """{args.ac_id}: {args.scenario}."""
    # 1. 准备 (启动服务/构造数据)
    # ...

    # 2. 执行 (浏览器操作)
    # page.goto("/...")
    # page.fill(...)
    # page.click(...)

    # 3. 断言 (按 interfaces.md 出口断言)
    # assert page.url.endswith("/...")
    # assert page.locator("...").text_content() == "..."
''',
        'testclient': f'''"""E2E test: {args.scenario} (AC: {args.ac_id}).

Generated by lk shield scaffold. Test framework: TestClient (HTTP).
"""
import pytest
from fastapi.testclient import TestClient


@pytest.mark.e2e
def test_{args.scenario}(client: TestClient):
    """{args.ac_id}: {args.scenario}."""
    # 1. 准备
    # ...

    # 2. 执行 (API 调用)
    # response = client.get("/...")
    # response = client.post("/...", json={{...}})

    # 3. 断言 (按 interfaces.md 出口断言)
    # assert response.status_code == 200
    # assert "..." in response.json()
''',
        'db': f'''"""E2E test: {args.scenario} (AC: {args.ac_id}).

Generated by lk shield scaffold. Test framework: 直查 DB.
"""
import pytest


@pytest.mark.e2e
def test_{args.scenario}():
    """{args.ac_id}: {args.scenario}."""
    # 1. 准备 (DB 连接)
    # conn = get_db_connection()

    # 2. 执行 (查询/操作)
    # row = conn.execute("...").fetchone()

    # 3. 断言 (按 interfaces.md 出口断言)
    # assert row["state"] == "..."
''',
    }

    template = templates[args.type]
    target_file.write_text(template)
    print(f"✓ Scaffold created: {target_file}")
    return 0