"""E2E: FR-0100 M-DESIGN entry (extension beyond required suite).

Verifies the M-DESIGN entry preconditions are observable through the
Workbench public surface. AC-FR0100-01 is not in the required e2e suite,
but the entry precondition (approved requirements current) is exercised
by both journeys, so we assert it here as an extension.
"""

from __future__ import annotations

import pytest

pytestmark = pytest.mark.v014_002_e2e


def test_m_design_entry_requires_approved_requirements(design_manifest):
    """M-DESIGN entry requires an approved requirements baseline."""
    inputs = design_manifest.get("input_artifacts", [])
    # The Archer task manifest is the Runtime dispatch readback.
    kinds = {entry.get("kind") for entry in inputs}
    assert "archer-author-task-manifest" in kinds, (
        "M-DESIGN entry requires archer-author-task-manifest input"
    )


def test_m_design_entry_binds_base_commit(e2e_test_contract):
    """M-DESIGN entry must bind a precise base commit."""
    scope = e2e_test_contract.get("scope", {})
    base_commit = scope.get("base_commit")
    assert base_commit
    assert isinstance(base_commit, str)
    # Must be a 40-char hex sha (not a branch name).
    assert len(base_commit) == 40
    int(base_commit, 16)  # raises ValueError if not hex


def test_m_design_entry_binds_project_facts_digest(e2e_test_contract):
    """M-DESIGN entry must bind a project_facts_digest."""
    scope = e2e_test_contract.get("scope", {})
    digest = scope.get("project_facts_digest", "")
    assert digest.startswith("sha256:")
    # Hex digest after prefix.
    hex_part = digest.removeprefix("sha256:")
    assert len(hex_part) == 64
    int(hex_part, 16)


def test_m_design_entry_binds_release_identity(e2e_test_contract):
    """M-DESIGN entry must bind release_identity = 0.14.0."""
    scope = e2e_test_contract.get("scope", {})
    assert scope.get("release_identity") == "0.14.0"


def test_m_design_entry_binds_workspace(e2e_test_contract):
    """M-DESIGN entry must bind workspace_id = github.com/zillionare/louke."""
    scope = e2e_test_contract.get("scope", {})
    assert scope.get("workspace_id") == "github.com/zillionare/louke"


@pytest.mark.awaiting_devon("FR-0100")
def test_m_design_entry_visible_through_workbench(workbench_api):
    """M-DESIGN entry must be visible through the Workbench public surface."""
    assert workbench_api is not None


def test_m_design_entry_generated_by_archer(e2e_test_contract):
    """M-DESIGN entry must be generated by Archer role."""
    generated_by = e2e_test_contract.get("generated_by", {})
    assert generated_by.get("role") == "Archer"
    assert generated_by.get("owner") == "Runtime/program"


def test_m_design_entry_compatible_runtime(e2e_test_contract):
    """compatible_runtime must declare the 0.14.x range."""
    compatible = e2e_test_contract.get("compatible_runtime", "")
    assert "0.14.0" in compatible
    assert compatible.startswith(">=")
